### ISSUE TITLE
update the snakePipes installed from the github

### ISSUE THREAD

**Issue by sunta3iouxos** [kilpert/snakemake_workflows#1007]
Hi all,
I have not been able to find an appropriate ansewer in the readthedoc page, so could you please let me know how I can properly update to the lattest commits my snakePipes environment?
I had used those steps to generate it:
```bash
git clone -b develop https://github.com/maxplanck-ie/snakepipes.git snakepipes_develop
mamba create -n snakePipes_devel python=3.11 pip
mamba activate snakePipes_devel
cd snakepipes_develop
pip install --upgrade .
```
do I need to repeat the steps but use:
```bash
cd snakepipes_develop
git pull
mamba activate snakePipes_devel
pip install --upgrade .
```

**Comment by WardDeb** [comment]
Pip install instructions live under pairtools branch, to go live in the 3.0.0 release
