### ISSUE TITLE
DNA-mapping error: [main_samview] fail to read the header from "-".

### ISSUE THREAD

**Issue by blin100** [kilpert/snakemake_workflows#646]
Hi, I'm trying to run a few fastq samples through DNA-mapping, so I can get to the ATAC-seq pipeline. I'm running into this problem during the Bowtie2 step:

```
Activating conda environment: /home/bl141/.conda/envs/c12842aea6bc836046a0c5fcc8df90e8
[main_samview] fail to read the header from "-".
[Wed Jun 10 11:05:51 2020]
Error in rule Bowtie2:
    jobid: 0
    output: Bowtie2/BL1.Bowtie2_summary.txt, Bowtie2/BL1.sorted.bam
    log: Bowtie2/logs/BL1.sort.log (check log file(s) for error message)
    conda-env: /home/bl141/.conda/envs/c12842aea6bc836046a0c5fcc8df90e8
    shell:
        
            TMPDIR=/n/scratch3/users/b/bl141/tmp
            MYTEMP=$(mktemp -d ${TMPDIR:-/tmp}/snakepipes.XXXXXXXXXX);
            bowtie2             -X 1000             -x /ref/snakepipeRef/GRCm38_gencode_release19/BowtieIndex/genome -1 FASTQ/BL1_1.fastq.gz -2 FASTQ/BL1_2.fastq.gz              --fr             --rg-id BL1             --rg DS:BL1 --rg PL:ILLUMINA --rg SM:BL1             -p 20             2> Bowtie2/BL1.Bowtie2_summary.txt |             samtools view -Sb - |             samtools sort -m 2G -T $MYTEMP/BL1 -@ 2 -O bam - > Bowtie2/BL1.sorted.bam 2> Bowtie2/logs/BL1.sort.log;
            rm -rf $MYTEMP
            
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
```

Does anyone have any advice?
Tool versions:  - deeptools = 3.3.2
 - seqtk = 1.3
 - pigz = 2.3.4
 - snpsplit = 0.3.4
 - samtools = 1.10
 - fastqc = 0.11.9
 - cutadapt = 2.8
 - trim-galore = 0.6.5
 - multiqc = 1.8
 - fastp = 0.20.0
 - umi_tools = 1.0.1
 - bowtie2 = 2.3.5.1
 - qualimap = 2.2.2d
 - samtools = 1.10

**Comment by vitaly001** [comment]
Hi Brain, I got same error message and I'm tryin g to deal with this. Could you please tell me what kind of typo you did in yaml file (and what yaml file should I look for)
Thanks

**Comment by blin100** [comment]
Argh, I'm sorry, but I absolutely have no memory of what the typo was. I feel like it was the yaml in the DNA mapping folder, snakePipes/workflows/DNA-mapping/defaults.yaml, but to be honest, it was so long ago, and I don't use this tool anymore, that I can't really help at all. Sorry!

**Comment by vitaly001** [comment]
OK. I hope somebody else can help me. 
Thanks

**Comment by katsikora** [comment]
Hi Vitaly,

did you try the solution above i.e. entering commands one by one to see which one fails? Just update them to what is appropriate for you. You should have all the commands in the bowtie2 cluster log file in cluster_logs folder.
Also, running snakePipes workflows with "--verbose" will print all shell commands in the main workflow log file.

###############################################################################################
Ok, you can try out the single commands manually for this one sample.

    cd into your main output folder
    conda/source activate /home/bl141/.conda/envs/c12842aea6bc836046a0c5fcc8df90e8
    bowtie2 -X 1000 -x /ref/snakepipeRef/GRCm38_gencode_release19/BowtieIndex/genome -1 FASTQ/BL1_1.fastq.gz -2 FASTQ/BL1_2.fastq.gz --fr --rg-id BL1 --rg DS:BL1 --rg PL:ILLUMINA --rg SM:BL1 -p 20 > test.sam 2> Bowtie2/BL1.Bowtie2_summary.txt
    4)check this summary and any other bowtie2 output
    5)samtools view -Sb test.sam > test.bam
    6)TMPDIR=/n/scratch3/users/b/bl141/tmp
    7)MYTEMP=$(mktemp -d ${TMPDIR:-/tmp}/snakepipes.XXXXXXXXXX)
    8)samtools sort -m 2G -T $MYTEMP/BL1 -@ 2 -O bam test.bam > Bowtie2/BL1.sorted.bam
    9)rm -rf $MYTEMP

Maybe you can single out what is actually throwing the error.
